name: fitness_tracker_app
version: 1.0.0+1
publish_to: none
description: A fitness tracker App
environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.1.5
  iconly: ^1.0.1
  lottie: ^2.6.0
  google_fonts:
  get: 4.6.6
  flutter:
    sdk: flutter
  firebase_core: ^2.16.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

