// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhQTsBhUdpvg4aEihubnhrcNM5P-a4xsY',
    appId: '1:1006476145311:android:a9874ebcc9488787ef68aa',
    messagingSenderId: '1006476145311',
    projectId: 'fitness-tracker-e32f7',
    storageBucket: 'fitness-tracker-e32f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMZ230GCSzpyoDoSWgw7xJ4uldCwpxGZ4',
    appId: '1:1006476145311:ios:12297a8a42ff8561ef68aa',
    messagingSenderId: '1006476145311',
    projectId: 'fitness-tracker-e32f7',
    storageBucket: 'fitness-tracker-e32f7.appspot.com',
    androidClientId: '1006476145311-7gladv8b7u003p2iat844jh3ntdbb09c.apps.googleusercontent.com',
    iosClientId: '1006476145311-9tj15jscur51j2i1gmn4nf01ejbcq11q.apps.googleusercontent.com',
    iosBundleId: 'app.fitness.fitnessTrackerApp',
  );
}
